In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
#Reading MaternalHealth dataset
data = pd.read_csv('MaternalHealth.csv')

In [4]:
#Reading MaternalHealth dataset first give rows
data.head(5)

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [5]:
#Checking MaternalHealth dataset missing values
data.isnull().sum()

Age            0
SystolicBP     0
DiastolicBP    0
BS             0
BodyTemp       0
HeartRate      0
RiskLevel      0
dtype: int64

In [6]:
#information of MaternalHealth dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1014 non-null   int64  
 1   SystolicBP   1014 non-null   int64  
 2   DiastolicBP  1014 non-null   int64  
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64  
 6   RiskLevel    1014 non-null   object 
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB


In [ ]:
#Extracting PCA Features
from sklearn.decomposition import PCA

X = data.drop('species',axis=1)
Y = data['species']

PCA_TR = PCA(n_components=3)
X_train = PCA_TR.fit_transform(X)
PCA_TR.explained_variance_ratio_

In [ ]:
PCA_TR.components_

In [ ]:
pd.DataFrame(PCA_TR.components_,columns=X.columns,index = ['PC-1','PC-2','PC-3'])

In [ ]:
#Kfold results
from sklearn.model_selection import StratifiedKFold,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

LRM = LogisticRegression()
DTC = DecisionTreeClassifier()
RFC = RandomForestClassifier()
KNC = KNeighborsClassifier()
NBC = GaussianNB()

SKF = StratifiedKFold(n_splits = 10, shuffle =True, random_state=10)

print(f'LogisticRegression : {round(cross_val_score(LRM,X_train,Y,cv=SKF,scoring="accuracy").mean()*100,2)}%')
print(f'DecisionTreeClassifier : {round(cross_val_score(DTC,X_train,Y,cv=SKF,scoring="accuracy").mean()*100,2)}%')
print(f'RandomForestClassifier : {round(cross_val_score(RFC,X_train,Y,cv=SKF,scoring="accuracy").mean()*100,2)}%')
print(f'KNeighborsClassifier : {round(cross_val_score(KNC,X_train,Y,cv=SKF,scoring="accuracy").mean()*100,2)}%')
print(f'GaussianNB : {round(cross_val_score(NBC,X_train,Y,cv=SKF,scoring="accuracy").mean()*100,2)}%')

In [ ]:
from sklearn.ensemble import RandomForestClassifier

y=data["RiskLevel"]
x=data.drop(["RiskLevel"], axis=1)
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
le = preprocessing.LabelEncoder()

In [ ]:
#all PCA features models
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=100, random_state=52)
pred = rfc.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,pred))
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=52)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,xgb_pred))
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report
dt = DecisionTreeClassifier(random_state=50)
print("Decision Tree Classifier Result")
DecisionTree=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,DecisionTree))
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=2.0, random_state=52)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print("ETC")
b = ExtraTreesClassifier(n_estimators=100, random_state=52)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,b_pred))
from sklearn.naive_bayes import MultinomialNB
print("MultinomialNB NB")
gnb = MultinomialNB()
gnb_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,gnb_pred))
# Fitting XGBoost to the training data
XGBClassifier = xgb.XGBClassifier()
XGBoost=my_model.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,XGBoost))
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print("Logistic Regression Result")
logisticRegresion=lr.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,logisticRegresion))

from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
print("Stochastic Gradient Classifier")
clf = SGDClassifier(max_iter=1100, tol=1e-3)
calibrated_clf = CalibratedClassifierCV(clf, cv=5, method='isotonic')
predSGD=calibrated_clf.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predSGD))

#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
#from sklearn.linear_model import SGDClassifier
print("Voting Classifier XGB+RF+ETC")
clf1 = xgb.XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=52)
clf3 = ExtraTreesClassifier(n_estimators=100, random_state=52)
eclf1 = VotingClassifier(estimators=[
        ('xgb', clf1), ('rf', clf2), ('etc', clf3)],voting='hard')
predictionVC=eclf1.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predictionVC))

In [ ]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, shuffle=True)

In [ ]:
len(y_train)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=50)
dtPre=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,dtPre))
print(classification_report(y_test,dtPre))
print(confusion_matrix(y_test,dtPre))

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
print("ADA")
xgb = AdaBoostClassifier(n_estimators=200, random_state=5)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,xgb_pred))
print(confusion_matrix(y_test,xgb_pred))

In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=1.0, random_state=500)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200, random_state=5, max_depth=20)
rfc.fit(X_train, y_train)
# calculate accuracy of class predictions
y_pred_class = rfc.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
print("ETC")
b = ExtraTreesClassifier(n_estimators=200, random_state=5, max_depth=20)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,b_pred))
print(confusion_matrix(y_test,b_pred))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='liblinear',multi_class='ovr',C=3.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


In [ ]:
from sklearn.linear_model import SGDClassifier
r3=SGDClassifier(max_iter=1000, tol=1e-3,loss='perceptron')
x=r3.fit(X_train, y_train)

y_pred_class = r3.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
r1 = LogisticRegression(random_state=1000, solver='liblinear',multi_class='ovr',C=3.0)
r2 = SVC(kernel='linear', C=1.0, random_state=500,probability=True)
r3 = SGDClassifier(max_iter=1000, tol=1e-3,loss='perceptron')
er = VotingClassifier([('lr', r1),('svc', r2),('sgdc', r3)],voting="hard")

x=er.fit(X_train, y_train)

y_pred_class = er.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


In [ ]:
import numpy as np # linear algebra

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
import glob
import cv2
import tensorflow as tf
from keras import layers
from keras.layers import Dropout , Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
from keras.initializers import glorot_uniform
from sklearn.model_selection import train_test_split
import keras.backend as K
from sklearn.utils import shuffle
# importing all necessary libraries to run the code
import re,string
import numpy as np
import pandas as pd
import keras_metrics
import tensorflow.keras
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation,Embedding
# using the variable sw to hold all stopwords that are in English
sw = stopwords.words('english')

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le = preprocessing.LabelEncoder()
y = le.fit_transform(target)

In [ ]:
X_train_res=df.astype(int)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=50)
dtPre=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,dtPre))
print(classification_report(y_test,dtPre))
print(confusion_matrix(y_test,dtPre))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200, random_state=5, max_depth=20)
rfc.fit(X_train, y_train)
# calculate accuracy of class predictions
y_pred_class = rfc.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
print("ETC")
b = ExtraTreesClassifier(n_estimators=300, random_state=5, max_depth=20)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,b_pred))
print(confusion_matrix(y_test,b_pred))

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=5)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,xgb_pred))
print(confusion_matrix(y_test,xgb_pred))

In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
r1 = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
r2 = SVC(kernel='linear', C=1.0, random_state=2, probability=True)
r3=SGDClassifier(loss='perceptron')
er = VotingClassifier([('svc', r2),('lr', r1),('sgdc', r3)],voting="hard")

x=er.fit(X_train, y_train)

y_pred_class = er.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


              precision    recall  f1-score   support

           0       0.81      0.81      0.81        26
           1       0.86      0.86      0.86        35

    accuracy                           0.84        61
   macro avg       0.83      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

[[21  5]
 [ 5 30]]


In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='sigmoid', C=1.0, random_state=2)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

SVC
              precision    recall  f1-score   support

           0       0.79      0.85      0.81        26
           1       0.88      0.83      0.85        35

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61

[[22  4]
 [ 6 29]]


In [ ]:
#PCA feature data
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=100, random_state=52)
pred = rfc.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,pred))
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=52)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,xgb_pred))
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report
dt = DecisionTreeClassifier(random_state=50)
print("Decision Tree Classifier Result")
DecisionTree=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,DecisionTree))
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=2.0, random_state=52)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print("ETC")
b = ExtraTreesClassifier(n_estimators=100, random_state=52)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,b_pred))
from sklearn.naive_bayes import MultinomialNB
print("MultinomialNB NB")
gnb = MultinomialNB()
gnb_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,gnb_pred))
# Fitting XGBoost to the training data
XGBClassifier = xgb.XGBClassifier()
XGBoost=my_model.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,XGBoost))
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print("Logistic Regression Result")
logisticRegresion=lr.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,logisticRegresion))

from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
print("Stochastic Gradient Classifier")
clf = SGDClassifier(max_iter=1100, tol=1e-3)
calibrated_clf = CalibratedClassifierCV(clf, cv=5, method='isotonic')
predSGD=calibrated_clf.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predSGD))

#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
#from sklearn.linear_model import SGDClassifier
print("Voting Classifier XGB+RF+ETC")
clf1 = xgb.XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=52)
clf3 = ExtraTreesClassifier(n_estimators=100, random_state=52)
eclf1 = VotingClassifier(estimators=[
        ('xgb', clf1), ('rf', clf2), ('etc', clf3)],voting='hard')
predictionVC=eclf1.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predictionVC))

In [ ]:
#PCA features data
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=100, random_state=52)
pred = rfc.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,pred))
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=52)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,xgb_pred))
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report
dt = DecisionTreeClassifier(random_state=50)
print("Decision Tree Classifier Result")
DecisionTree=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,DecisionTree))
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=2.0, random_state=52)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print("ETC")
b = ExtraTreesClassifier(n_estimators=100, random_state=52)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,b_pred))
from sklearn.naive_bayes import MultinomialNB
print("MultinomialNB NB")
gnb = MultinomialNB()
gnb_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,gnb_pred))
# Fitting XGBoost to the training data
XGBClassifier = xgb.XGBClassifier()
XGBoost=my_model.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,XGBoost))
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print("Logistic Regression Result")
logisticRegresion=lr.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,logisticRegresion))

from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
print("Stochastic Gradient Classifier")
clf = SGDClassifier(max_iter=1100, tol=1e-3)
calibrated_clf = CalibratedClassifierCV(clf, cv=5, method='isotonic')
predSGD=calibrated_clf.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predSGD))

#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
#from sklearn.linear_model import SGDClassifier
print("Voting Classifier XGB+RF+ETC")
clf1 = xgb.XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=52)
clf3 = ExtraTreesClassifier(n_estimators=100, random_state=52)
eclf1 = VotingClassifier(estimators=[
        ('xgb', clf1), ('rf', clf2), ('etc', clf3)],voting='hard')
predictionVC=eclf1.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predictionVC))

In [ ]:
#MLP Multi-layer perceptron

In [ ]:
# Set up the number of perceptron per each layer:
p=4 # Layer 1
q=4 # Layer 2

# Set up the Learning rate
eta =  1/623


# 0: Random initialize the relevant data
w1 = 2*np.random.rand(p , X_train.shape[1]) - 0.5 # Layer 1
b1 = np.random.rand(p)

w2 = 2*np.random.rand(q , p) - 0.5  # Layer 2
b2 = np.random.rand(q)

wOut = 2*np.random.rand(q) - 0.5  # Output Layer
bOut = np.random.rand(1)

mu = []
vec_y = []

# Start looping over the passengers, i.e. over I.

for I in range(0, X_train.shape[0]): #loop in all the passengers:

    # 1: input the data
    x = X_train[I]


    # 2: Start the algorithm

    # 2.1: Feed forward
    z1 = ReLU_act(np.dot(w1, x) + b1) # output layer 1
    z2 = ReLU_act(np.dot(w2, z1) + b2) # output layer 2
    y = sigmoid_act(np.dot(wOut, z2) + bOut) # Output of the Output layer

    #2.2: Compute the output layer's error
    delta_Out =  (y-Y_train[I]) * sigmoid_act(y, der=True)

    #2.3: Backpropagate
    delta_2 = delta_Out * wOut * ReLU_act(z2, der=True) # Second Layer Error
    delta_1 = np.dot(delta_2, w2) * ReLU_act(z1, der=True) # First Layer Error

    # 3: Gradient descent
    wOut = wOut - eta*delta_Out*z2  # Outer Layer
    bOut = bOut - eta*delta_Out

    w2 = w2 - eta*np.kron(delta_2, z1).reshape(q,p) # Hidden Layer 2
    b2 = b2 - eta*delta_2

    w1 = w1 - eta*np.kron(delta_1, x).reshape(p, x.shape[0]) # Hidden Layer 1
    b1 = b1 - eta*delta_1

    # 4. Computation of the loss function
    mu.append((1/2)*(y-Y_train[I])**2)
    vec_y.append(y[0])


# Plotting the Cost function for each training data
plt.figure(figsize=(10,6))
plt.scatter(np.arange(0, X_train.shape[0]), mu, alpha=0.3, s=4, label='mu')
plt.title('Loss for each training data point', fontsize=20)
plt.xlabel('Training data', fontsize=16)
plt.ylabel('Loss', fontsize=16)
plt.show()

# Plotting the average cost function over 10 training data
pino = []
for i in range(0, 9):
    pippo = 0
    for m in range(0, 59):
        pippo+=vec_y[60*i+m]/60
    pino.append(pippo)



plt.figure(figsize=(10,6))
plt.scatter(np.arange(0, 9), pino, alpha=1, s=10, label='error')
plt.title('Averege Loss by epoch', fontsize=20)
plt.xlabel('Epoch', fontsize=16)
plt.ylabel('Loss', fontsize=16)
plt.show()


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


              precision    recall  f1-score   support

           0       0.94      0.85      0.89        93
           1       0.86      0.95      0.90        91

    accuracy                           0.90       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.90      0.90      0.90       184

[[79 14]
 [ 5 86]]


In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='sigmoid', C=1.0, random_state=2)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


SVC
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        93
           1       0.86      0.95      0.90        91

    accuracy                           0.90       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.90      0.90      0.90       184

[[79 14]
 [ 5 86]]


In [ ]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(rounded_predictions, target, test_size=0.20, shuffle=True)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
print("ETC")
b = ExtraTreesClassifier(n_estimators=300, random_state=5, max_depth=20)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,b_pred))
print(confusion_matrix(y_test,b_pred))

ETC
              precision    recall  f1-score   support

           0       0.83      0.85      0.84        73
           1       0.90      0.88      0.89       111

    accuracy                           0.87       184
   macro avg       0.86      0.87      0.86       184
weighted avg       0.87      0.87      0.87       184

[[62 11]
 [13 98]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=5)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,xgb_pred))
print(confusion_matrix(y_test,xgb_pred))

ADA
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        73
           1       0.86      0.86      0.86       111

    accuracy                           0.84       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.84      0.84      0.84       184

[[58 15]
 [15 96]]


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
r1 = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
r2 = SVC(kernel='sigmoid', C=1.0, random_state=2, probability=True)
er = VotingClassifier([('lr', r1),('svc', r2)],voting="soft")

x=er.fit(X_train, y_train)

y_pred_class = er.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


              precision    recall  f1-score   support

           0       0.82      0.85      0.83        73
           1       0.90      0.87      0.89       111

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184

[[62 11]
 [14 97]]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84        66
           1       0.84      0.88      0.86        72

    accuracy                           0.85       138
   macro avg       0.85      0.85      0.85       138
weighted avg       0.85      0.85      0.85       138

[[54 12]
 [ 9 63]]


In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='sigmoid', C=2.0, random_state=2)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


SVC
              precision    recall  f1-score   support

           0       0.84      0.82      0.83        66
           1       0.84      0.86      0.85        72

    accuracy                           0.84       138
   macro avg       0.84      0.84      0.84       138
weighted avg       0.84      0.84      0.84       138

[[54 12]
 [10 62]]


In [ ]:
def nearest_on_circle(c, R, x):
    cos_=(x2-c2)/euclidean_dist(x1,x2,c1,c2)
    sin_=(x1-c1)/euclidean_dist(x1,x2,c1,c2)
    #then extrpolate the center along this line to a distance equal to that of radius
    #to obtain the nearest point
    y1=c1+r*cos_
    y2=c2+r*sin_
    y=y1,y2
    return y

In [ ]:
def euclidean_dist(x1,y1,x2,y2):
    return math.sqrt((x1-x2)**2 +(y1-y2)**2)

In [ ]:
def reflections_in_tunnel(w, h, alpha, n):
    x=(n*w-h)/math.tan(alpha)
    return x

In [ ]:
reflections_in_tunnel(2, 3, 30, 1)

0.15611995216165922

In [ ]:
def reflection_on_circle(c_x, R, alpha):
    #formula to find Sin Beta
    sinB=(c_x/R)*math.sin(alpha)
    # Now L will be
    L=c_x+(R*sinB)/(math.cos(alpha)*(1-2*math.sin(sinB)**2)-(2*math.sin(alpha)*math.sin(sinB))*(math.sqrt(1-math.sin(sinB)**2)))
    return L

In [ ]:
B=[[1,0],[1,0],[1,0]]
v=[1,2,2]
B=np.array(B)
v=np.array(v)



In [ ]:
import numpy as np
x = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
y = ([[3.65], [1.55], [3.42]])
x = np.array(x)
scalars = np.linalg.solve(x, y)
scalars

array([[3.42],
       [1.55],
       [3.65]])

In [ ]:
from scipy.linalg import orth
o=orth(x)
v=scalars+o
v

array([[3.42, 3.42, 2.42],
       [1.55, 2.55, 1.55],
       [2.65, 3.65, 3.65]])

In [ ]:
def orthogonal_components(B, v):
    B = np.array(B)
    v = np.array(v)
    v11 = np.linalg.solve(x, y)
    from scipy.linalg import orth
    vp=orth(x)
    return v11,vp

In [ ]:
orthogonal_components(x,y)

(array([[3.42],
        [1.55],
        [3.65]]),
 array([[ 0.,  0., -1.],
        [ 0.,  1.,  0.],
        [-1.,  0.,  0.]]))

In [ ]:
def marginal_x(P):
    p=np.array(P)
    from scipy.stats.contingency import margins
    x, y = margins(p)
    return x.T

In [ ]:
import numpy as np


p = np.array([[0.01, 0.02, 0.04, 0.04],
                [0.03, 0.24, 0.15, 0.06],
                [0.04, 0.10, 0.08, 0.08],
                [0.02, 0.04, 0.03, 0.02]
            ])


a=marginal_x(p)
a=np.array(a)
print(marginal_x(p))

[[0.11 0.48 0.3  0.11]]


In [ ]:
def calc_Expectation(P):
		p=np.array(P)
		sum = 0
		from scipy.stats.contingency import margins
		x, y = margins(p)
		a=np.array(y.T)
		for i in range(len(a)):
			sum=sum+ (a[i])
		e=float(sum)
		return e



In [ ]:
def calc_Expectation(P):
		p=np.array(P)
		sum = 0
		from scipy.stats.contingency import margins
		x, y = margins(p)
		a=np.array(y.T)
		a=np.array(y.T)



In [ ]:
calc_Expectation(p)

1.0

In [ ]:
def calc_Expectation(P, n):
		prb = 1 / n
		sum = 0
		p=np.array(P)
		from scipy.stats.contingency import margins
		x, y = margins(p)
		a=np.array(x*y.T)


In [ ]:
p = np.array([[0.01, 0.02, 0.04, 0.04],
                [0.03, 0.24, 0.15, 0.06],
                [0.04, 0.10, 0.08, 0.08],
                [0.02, 0.04, 0.03, 0.02]
            ])


n=2
calc_Expectation(p,n)

0.1015

In [ ]:
def repeated_entries(x):
    a=np.array(x.T)
    N = len(x)
    L=len(a)
    S = np.zeros((N, L))
    u = a
    return S, u

x=np.array([3,4,4,5,6,7])
repeated_entries(x)

(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 array([3, 4, 4, 5, 6, 7]))